services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - "4242:3306"
    env_file: ".env"
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress_php
    ports:
      - "443:443"
    volumes:
      - wp-website:/var/www/html
    restart: always 
    networks:
      - inception

  wordpress_php:
    build: ./requirements/wordpress_php
    container_name: wordpress_php
    depends_on:
      - mariadb
    env_file: ".env"
    restart: always
    volumes:
      - wp-website:/var/www/html
    networks:
      - inception

  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    depends_on:
      - mariadb
      - wordpress_php
    ports:
      - "9000"
    restart: always
    volumes:
      - wp-website:/var/www/html
    networks:
      - inception

  website:
    build: ./requirements/bonus/static_website
    container_name: website
    depends_on:
      - wordpress_php
    ports:
      - "9000"
    restart: always
    networks:
      - inception

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    depends_on:
      - mariadb
      - wordpress_php
    ports:
      - "6379"
    restart: always
    networks:
      - inception

  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    depends_on:
      - wordpress_php
    env_file: ".env"
    ports:
      - "21:21"
      - "20000-20010:20000-20010"
    restart: always
    volumes:
      - wp-website:/home/$FTP_USER/ftp/files
    networks:
      - inception

  cadvisor:
    build: ./requirements/bonus/service
    container_name: cadvisor
    ports:
      - "8080:8080"
    networks:
      - inception
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    restart: always

volumes:
  mariadb-data:
    driver: local
    name: mariadb-data
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ~/data/mariadb

  wp-website:
    driver: local
    name: wp-website
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ~/data/wp-website

networks:
  inception:
    name: inception
    driver: bridge
