services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - "4242:3306"
    env_file: ".env"
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress_php
    ports:
      - "443:443"
    volumes:
      - wp-website:/var/www/html
    restart: always 
    networks:
      - inception

  wordpress_php:
    build: ./requirements/wordpress_php
    container_name: wordpress_php
    depends_on:
      - mariadb
    env_file: ".env"
    restart: always
    volumes:
      - wp-website:/var/www/html
    networks:
      - inception

  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    depends_on:
      - mariadb
    ports:
      - "9000"
    restart: always
    volumes:
      - wp-website:/var/www/html
    networks:
      - inception

volumes:
  mariadb-data:
    driver: local
    name: mariadb-data
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ~/data/mariadb

  wp-website:
    driver: local
    name: wp-website
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ~/data/wp-website

networks:
  inception:
    name: inception
    driver: bridge
